;;; local_packages/colorize/colorize.el -*- lexical-binding: t; -*-

;; DONE move from test.el
;; DONE cleanup naming conventions
;; DONE support oscillation
;; <NOT NEEDED> break up coloriz-hl-line function to subfunctions for advising purposes
;; - tick
;; - setting color
;; - getting next color
;; - cleanup
;; DONE make public interp function
;; - change things to defvar for documentation
;; DONE leave-me-alone command
;; DONE set idle timer command
;; DONE config to colorize highlight as well
;; - add list of faces that also get colorized -> (or change it to list all together)
;; - use hl-line as default
;; TODO coloirze any aspect of face, not just background
;; - refactor big
;; - now have n interpolations going at once, each with their own state, starting and target colors
;; TODO getters and setter for random ranges
;; TODO config to disable revertion when moving cursor
;; TODO rename package to "colorize" (or something to do with lerping colors over time idly)

(eval-when-compile (require 'cl-lib))

(setq colorize-step-size 0.01) ;; TODO defvar

(cl-defstruct (colorize--interp-datum (:constructor colorize--interp-datum-create)
                                 (:copier nil))
  (face nil :documentation "Affected face")
  (specs '() :documentation "List of faces that are affected (should be `foreground', `background', or `distantforeground')")
  (start-color nil :documentation "Start color interpolated")
  (end-color nil :documentation "End color interpolated")
  (progress 0.0 :documentation "Current interpolation progress")
  (interp-func #'colorize-interpolate-linear :documentation "Function used to interpolate values")
  (next-color-func #'colorize--get-random-hsl-color :documentation "Function used to determine next color")
  (color-list '() :documentation "List of colors used by next-color-func")
  (color-list-index 0 :documentation "Index used in next-color-func")
  (cookies '() :documentation "List of cookies generated by `face-remap-add-relative'")
  (step-multiple 1.0 :documentation "Multiplier on how much to modify speed of interpolation"))

(defun colorize--init-interp-datum (face specs &rest rest)
  (let (
        (interp-func (plist-get rest :interp-func))
        (next-color-func (plist-get rest :next-color-func))
        (color-list (plist-get rest :color-list))
        (step-multiple (plist-get rest :step-multiple)))
  (colorize--interp-datum-create
   :face face
   :specs (if (listp specs) specs (list specs))
   :interp-func (if interp-func interp-func #'colorize-interpolate-linear)
   :next-color-func (if next-color-func next-color-func #'colorize--get-random-hsl-color)
   :color-list (if color-list color-list '())
   :step-multiple (if step-multiple step-multiple 1.0))))

(defvar colorize--interpolate-data '()
  "List of `colorize-interpolate-datum'")

(defvar colorize--idle-timer nil
  "Idle timer used to colorize")
(cl-defstruct (colorize--color (:constructor colorize--color-create)
                               (:copier nil))
  hue saturation luminance)

(defun colorize--hex-to-rgb (hex)
  "Converts hex string (2 digits per component) to rgb tuple"
  (cl-assert (length= hex 7) "hex string should have 2 digits per component")
  (let (
        (red
         (/ (string-to-number (substring hex 1 3) 16) 255.0))
        (green
         (/ (string-to-number (substring hex 3 5) 16) 255.0))
        (blue
         (/ (string-to-number (substring hex 5 7) 16) 255.0)))
    (list red green blue)))

(defun colorize--hex-to-hsl-color (color)
  "Converts hex string `color' to a `colorize--color'"
  (pcase (apply 'color-rgb-to-hsl (colorize--hex-to-rgb color))
    (`(,hue ,sat ,lum) (colorize--color-create :hue hue :saturation sat :luminance lum))
    (`(,_) error "Could not parse hl-line")))

(defun colorize--get-start-hl-line-color (interp-datum)
  "Returns the current background color of the hl-line as `colorize--color'"
  (let ((hsl (apply 'color-rgb-to-hsl (colorize--hex-to-rgb (face-attribute (colorize--interp-datum-face interp-datum) :background)))))
    (pcase hsl
      (`(,hue ,sat ,lum) (colorize--color-create :hue hue :saturation sat :luminance lum))
      (`(,_) error "Could not parse hl-line"))))

;; TODO setters for this that take in 2 args
(setq colorize--hue-low 0.0)
(setq colorize--hue-high 1.0)
(setq colorize--saturation-low 0.5)
(setq colorize--saturation-high 1.0)
(setq colorize--luminance-low 0.2)
(setq colorize--luminance-high 0.3)

(defun colorize--get-random-hsl-color (interp-datum)
  "Returns random `hl-line-hsl-color'"
  (colorize--color-create
   :hue (colorize--get-random-float-from colorize--hue-low colorize--hue-high)
   :saturation (colorize--get-random-float-from colorize--saturation-low colorize--saturation-high)
   :luminance (colorize--get-random-float-from colorize--luminance-low colorize--luminance-high)))

(defun colorize--get-random-float-from (lower upper)
  "Gets random float from in range [lower, upper].
`lower' and `upper' should be in range [0.0, 1.0]"
  (cl-assert (and (>= lower 0.0) (<= lower 1.0)) "lower is not in range [0, 1]")
  (cl-assert (and (>= upper 0.0) (<= upper 1.0)) "upper is not in range [0, 1]")
  (cl-assert (<= lower upper) "lower should be <= upper")
  (let* (
         (high-number 10000000000)
         (lower-int (truncate (* lower high-number)))
         (upper-int (truncate (* upper high-number))))
    (/ (* 1.0 (+ lower-int (random (- upper-int lower-int)))) high-number)))

(defun colorize--get-next-hsl-color (interp-datum)
   (if (length= (colorize--interp-datum-color-list interp-datum) 0)
       nil
     (if (colorize--interp-datum-color-list-index interp-datum)
         (setq (colorize--interp-datum-color-list-index interp-datum) 0)
      (setq colorize--colors-list-index (mod (1+ colorize--colors-list-index) (length (colorize--interp-datum-color-list interp-datum))))
      (nth colorize--interp-datum-color-list (colorize--interp-datum-color-list interp-datum)))))

(defun colorize--get-random-hsl-color-from-list (interp-datum)
   (if (length= (colorize--interp-datum-color-list interp-datum) 0)
       nil
     (if (colorize--interp-datum-color-list-index interp-datum)
         (setq (colorize--interp-datum-color-list-index interp-datum) 0)
      (setq colorize--colors-list-index (random (length (colorize--interp-datum-color-list interp-datum))))
      (nth colorize--interp-datum-color-list (colorize--interp-datum-color-list interp-datum)))))

(defun colorize--clamp (value low high)
  "Clamps `value' between `low' and `high'"
  (max (min value high) low))

(defun colorize-interpolate-linear (progress start end)
  "Returns new color that is the result of interplating the colors of `start' and `end' linearly.
`progress' is a float in the range [0, 1], but providing a value outside of that will extrapolate new values.
`start' and `end' are `colorize--color'"
  (let (
        (new-hue
         (colorize--clamp
          (+ (* (- 1 progress) (colorize--color-hue start)) (* progress (colorize--color-hue end))) 0 1))
        (new-sat
         (colorize--clamp
          (+ (* (- 1 progress) (colorize--color-saturation start)) (* progress (colorize--color-saturation end))) 0 1))
        (new-lum
         (colorize--clamp
          (+ (* (- 1 progress) (colorize--color-luminance start)) (* progress (colorize--color-luminance end))) 0 1)))
    (colorize--color-create :hue new-hue :saturation new-sat :luminance new-lum)))

(defun colorize--hsl-color-to-hex (hsl-color)
  "Converts `colorize--color' to hex string with 2 digits for each component"
  (let ((rgb (color-hsl-to-rgb
              (colorize--color-hue hsl-color)
              (colorize--color-saturation hsl-color)
              (colorize--color-luminance hsl-color))))
    (color-rgb-to-hex (nth 0 rgb) (nth 1 rgb) (nth 2 rgb) 2)))

(defun colorize--update-progress (new-progress interp-datum)
  (let (
        (progress (colorize--interp-datum-progress interp-datum))
        (multiple (colorize--interp-datum-step-multiple interp-datum)))
    (setq progress (+ progress (* new-progress multiple)))
    (if (>= progress 1.0)
        (progn (setq progress 0.0)
               (colorize--change-next-colors interp-datum)))
    (setf (colorize--interp-datum-progress interp-datum) progress)))


(defun colorize--reset-faces (interp-datum)
  (let (
       (cookies (colorize--interp-datum-cookies interp-datum)))
    (dolist (cookie cookies)
      (face-remap-remove-relative cookie))
    (setf (colorize--interp-datum-cookies interp-datum) '())))

(defun colorize--set-faces (interp-datum)
  (let* (
         (face (colorize--interp-datum-face interp-datum))
         (specs (colorize--interp-datum-specs interp-datum))
         (interp-func (colorize--interp-datum-interp-func interp-datum))
         (start-color (colorize--interp-datum-start-color interp-datum))
         (end-color (colorize--interp-datum-end-color interp-datum))
         (progress (colorize--interp-datum-progress interp-datum))
         (new-color
          (colorize--hsl-color-to-hex
           (funcall interp-func progress start-color end-color))))
    (if (member 'background specs)
        (progn
          (setf (colorize--interp-datum-cookies interp-datum)
                (push (face-remap-add-relative face :background new-color)
                      (colorize--interp-datum-cookies interp-datum)))))
    (if (member 'foreground specs)
        (progn
          (setf (colorize--interp-datum-cookies interp-datum)
                (push (face-remap-add-relative face :foreground new-color)
                      (colorize--interp-datum-cookies interp-datum)))))
    (if (member 'distant-foreground specs)
        (progn
          (setf (colorize--interp-datum-cookies interp-datum)
                (push (face-remap-add-relative face :distant-foreground new-color)
                      (colorize--interp-datum-cookies interp-datum)))))
    (face-spec-recalc face (selected-frame))))

(defun colorize--init-colors (interp-datum)
  (let ((next-color-func (colorize--interp-datum-next-color-func interp-datum)))
    (setf (colorize--interp-datum-start-color interp-datum)
          (colorize--get-start-hl-line-color interp-datum))
    (setf (colorize--interp-datum-end-color interp-datum)
          (funcall next-color-func interp-datum))))

(defun colorize--change-next-colors (interp-datum)
  (let (
        (end-color (colorize--interp-datum-end-color interp-datum))
        (next-color-func (colorize--interp-datum-next-color-func interp-datum)))
    (setf (colorize--interp-datum-start-color interp-datum) end-color)
    (setf (colorize--interp-datum-end-color interp-datum)
          (funcall next-color-func interp-datum))))

(defun colorize ()
  "Begin colorizing"
  (interactive)
  (mapc #'colorize--init-colors colorize--interpolate-data)
  (while (not (input-pending-p))
    (sit-for colorize-step-size)
    (dolist (datum colorize--interpolate-data)
      (colorize--update-progress colorize-step-size datum)
      (colorize--reset-faces datum)
      (colorize--set-faces datum)))
  (mapc #'colorize--reset-faces colorize--interpolate-data))

(defun colorize-stop-idle ()
  "Stops the colorization effect when idle"
  (interactive)
  (cancel-timer colorize--idle-timer)
  (setq colorize--idle-timer nil))

(defun colorize-when-idle (secs)
  "Starts the colorization effect. when idle for `secs' seconds"
  (setq colorize--idle-timer (run-with-idle-timer secs t 'colorize)))

;; TESTING ========================================

(setq colorize-faces '(hl-line  doom-modeline-evil-normal-state))

;; TODO reference this later
;; (setq test-specs '(:background "#ff0000" :foreground "#00ff00"))
;; (setq test-cookie (face-remap-add-relative 'mode-line test-specs))
;; (face-remap-remove-relative test-cookie)

(setq colorize--interpolate-data (list
                                  (colorize--init-interp-datum 'hl-line '(foreground) :step-multiple 2)
                                  (colorize--init-interp-datum 'hl-line '(background) :step-multiple 1)
                                  (colorize--init-interp-datum 'mode-line '(background) :step-multiple 4)
                                  (colorize--init-interp-datum ' '(background) :step-multiple 4)
                                  ))
(colorize--init-colors test)
(colorize--change-next-colors test)
(colorize--reset-faces test)
(colorize--set-faces test)
(colorize--update-progress 0.2 test)

(print colorize--interpolate-data)
